---
abstract: 'A persistent database for holding cpantesters stats'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.016, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Testers-TailLog-DB
provides:
  CPAN::Testers::TailLog::DB:
    file: lib/CPAN/Testers/TailLog/DB.pm
    version: '0.001000'
requires:
  perl: '5.006'
resources:
  bugtracker: https://github.com/kentnl/CPAN-Testers-TailLog-DB/issues
  repository: https://github.com/kentnl/CPAN-Testers-TailLog-DB
version: '0.001000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
